### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by longseespace** [innocenat/kindle-epub-fix#16]
Hey @innocenat, great tool!

I'm interested in acquiring the tool. How best can I reach you?

**Comment by innocenat** [comment]
Not sure what you mean by "acquiring". It's already open sourced under the most open license I could ever think off. You are free to use it however you liked.

If you want to acquire the primary domain https://kindle-epub-fix.netlify.app/ to add ads, etc, then my answer is a firm no.

**Comment by longseespace** [comment]
Hey. I understand you don't want to turn this into a commercial tool. Me neither!

My proposal is to keep this free-forever, but would redirect/host it under my domain. So if people find my other services relevant then they _might_ give it a try. Totally fine if they don't.

My point is it would work the way you wanted, and would not add any annoyance to the users.

Would you interested in a chat?

**Comment by innocenat** [comment]
Unless it pertains to sensitive information, I prefer all conversion to be in public. If you do have sensitive information, my email address is available in the Git commit information.

> My proposal is to keep this free-forever, but would redirect/host it under my domain.

It is currently hosted under netlify because it was just a quick project when I began, so I didn't think much of it. I do have my own domain and server to host it myself should somehow netlify become paid service.

> So if people find my other services relevant then they might give it a try. Totally fine if they don't.

How about you link your service, and if I find it relevant, then I link to you?

**Comment by longseespace** [comment]
Great. Let's discuss all in public then. FYI, I've been building my startup in public, so big fan of transparency and all.

**So why am I doing this?**

I've been growing an indie product called KTool (https://ktool.io). It's a tool to send web articles, newsletters & RSS feeds to Kindle.

One of my grow strategy is to build free tools and give it away to gain traffic to the main product. People who are not interested in my product can use the tool for free, no ads, no BS. But some of those visitors might find my product useful and decide to buy. Win - Win.

Some of my free tools I launched: 

- Send Hacker News discussion to Kindle: https://ktool.io/hacker-news-to-kindle
- Send Reddit thread to Kindle: https://ktool.io/reddit-to-kindle
- Send AZW3 to Kindle wirelessly: https://ktool.io/azw3-to-kindle

As you can see, none of these tools include ads, and do not require an account.

I want to "acquire" the `kindle-epub-fix` tool because people find it useful, and the audience is a great fit for my product.

People are already linking to your page, so what I want is to host it under my domain (for SEO gain), and do a redirect from your current netlify page.

Alternatively, I'd love to have a link on your current page to my tool. Maybe as a sponsorship. Although this way, I do not have the SEO gain.

Let me know what you think

**Comment by innocenat** [comment]
I have definitely have heard of KTool before and while I haven't used it I have heard great thing about it. This does definitely make me less skeptics about this entire discussion. (Sorry about that)

I am willing to link to KTool without any compensation since I do genuinely think it's a great service. Please feel free to send a pull request adding your link in a manner you think is acceptable. At this point I am still reluctance to just redirect to your domain, sorry.

Just an additional note, though, if other Kindle related services that I deemed good enough also asked to be linked, I am likely to also accept them as well.

To be honest this tool's popularity has been been blown up kinda beyond my initial expectation and I honestly don't know what is the best option to proceed. I also don't have a lot of time to invest in it, either. It is currently hosted on Netlify free plan so I don't even have analytics on how many people access it each month.

**Comment by noahkiss** [comment]
> As you can see, none of these tools include ads, and do not require an account.

I don't see a way to access the free tools from the KTool landing page. In fact, I haven't found any direct link to the free tools anywhere else on the website. Maybe I missed something?

If not, this feels like a free sponsorship to a **paid** tool which **does** require an account, on the basis that there are "free" tools hosted on the site, but which will never actually be found unless someone comes to this thread or happens to find the specific pages via google.

Is my assumption incorrect? 

If not, I suggest reverting this disingenuous change or paying @innocenat an advertising fee (probably backdated, as I couldn't find a link to the free tools anywhere on wayback archive between May 2023 and now).

If my assumption *is* incorrect, I suggest adding prominent links to the free tools, at least for those visiting using the kindle-epub-fix referrer link.

**Comment by longseespace** [comment]
> If my assumption is incorrect, I suggest adding prominent links to the free tools, at least for those visiting using the kindle-epub-fix referrer link.

Honestly, it’s not on my homepage because I was lazy lol. I will add the links soon.

And did you read the whole thread? I _wanted_ to pay but @innocenat declined (thank you again)

**Comment by noahkiss** [comment]
> Honestly, it’s not on my homepage because I was lazy lol. I will add the links soon.

Hmm... it's hard to give you the benefit of the doubt on that statement, since you've had a year to add the links since your original request, plus your wording here directly contradicts your comment today:

> One of my grow strategy is to build free tools and give it away to gain traffic to the main product. People who are not interested in my product can use the tool for free, no ads, no BS. But some of those visitors might find my product useful and decide to buy.

Saying that visitors to your site will enjoy your free tools and use them without BS, with some converting to paid members, is almost impossible if you never actually guide visitors to your free tools, right? Anyone over the past year who has visited your site from the [kindle-epub-fix.netlify.app](https://kindle-epub-fix.netlify.app) website has had no chance to use those free tools because you were too "lazy" to link to them, right? Yet you weren't too lazy to come here, make an issue, follow up, open a PR, and add a link to a domain you *don't* own, right?

> And did you read the whole thread? I wanted to pay but @innocenat declined (thank you again)

The payment was declined because of the assumption that you were helping to provide (other) free tools to those visiting the [kindle-epub-fix.netlify.app](https://kindle-epub-fix.netlify.app) site, which is in line with @innocenat's principles & [un]license for this app. But I'd argue that you instead worded your reply in a way that used manipulation through perceived good faith to get out of paying for the backlink, and that you're trying to do it again by adding "(thank you again)" to the end of the above statement.

I think we both know what's going on here, and I think the right thing to do is to be up-front about it. You've already gotten almost a year of free linking, and since you use a referral query, I'd be interested in you sharing how much traffic you've gotten from [kindle-epub-fix.netlify.app](https://kindle-epub-fix.netlify.app) (since you've claimed you're open here and this isn't for your own personal gain). Those stats can then be used to determine what a fair market value of the advertising would have been, if @innocenat had all of the pertinent info when he entered into the agreement (since he said he doesn't have analytics).

**Comment by longseespace** [comment]
> Hmm... it's hard to give you the benefit of the doubt on that statement, since you've had a year to add the links

I stopped working on KTool exactly 1 year ago and this is only one of my many attempts at marketing. I don't even remember until you posted a message (which triggered a notification of course)

> Saying that visitors to your site will enjoy your free tools and use them without BS, with some converting to paid members, is almost impossible if you never actually guide visitors to your free tools, right

I never promise this to random website visitors. I explained to @innocenat what I meant when I said "acquiring" this tool, and what was my marketing strategy with full transparency. It's his decision to agree with my proposal or not. And if he's not happy with any of my proposal, he can remove the link any time. I don't understand _your_ problem here.

What are you accusing me of, exactly? Manipulating others? I wish I had such skill 😅

>  I think the right thing to do is to be up-front about it.

What is not up-front about my intention, I don't understand. I proposed to aquire the tool in the first place, and if not possible, hopelly I could sponsor it. To which @innocenat declined. And he was so kind that he said he will add the link to the tool, and any other tools if they are good (not just KTool)

> I'd be interested in you sharing how much traffic you've gotten from [kindle-epub-fix.netlify.app](https://kindle-epub-fix.netlify.app/)

About 1050 visitors. At 2% visit → signup conversion rate, that 21 signups. At 3% signups → paid conversion rate, that's less than 1 paid customer. And at $5/mo average order value, that's less than $60. And at 5% monthly churn rate, that's $30.

This is the reason I stopped working on KTool because it's not profitable for me.

![CleanShot 2024-05-09 at 04 19 59@2x](https://github.com/innocenat/kindle-epub-fix/assets/187720/c945eafb-ba01-4626-a723-e48ca2d69ee5)

> Those stats can then be used to determine what a fair market value of the advertising would have been

I agree in principal, but please note that there is no business agreement in this case. I wish @innocenat agreed to my initial proposal of acquiring this tool, but he didn't want to and I respect that.
